version: '3'

services:
    db-nux:
        container_name: db-nux
        image: mysql:8
        hostname: ${DB_HOST}
        restart: always
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-nux:/var/lib/mysql

    php-fpm-nux:
        container_name: php-fpm-nux
        build:
            context: ./docker/php
        ports:
            - "9007:9000"
        environment:
            DB_PORT: 3306
            DB_HOST: ${DB_HOST}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        restart: always
        networks:
            - nux-network
        depends_on:
            - ${DB_HOST}
        expose:
            - 9000

    nginx-nux:
        image: nginx:1.19
        container_name: nginx-nux
        restart: unless-stopped
        tty: true
        ports:
          - 8084:80
        volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - .:/var/www/html
        environment:
          - NGINX_PORT=80
        depends_on:
          - php-fpm-nux
          - ${DB_HOST}

    redis:
         image: redis:latest
         container_name: nux-redis
         command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
         volumes:
           - ./docker/redis:/data
         networks:
             - nux-network
         ports:
           - 6380:6379
         tty: true
         restart: always

volumes:
  db-nux:

networks:
    nux-network:
        driver: bridge

